### PR TITLE
support sync to github gist

### PR DESCRIPTION
**Pull request by tgxhx**
image 
This extension doesn't support Microsoft Edge and has issues with some other Chromium-core browsers, so I added the ability to sync to github gist.

### CODE REVIEW

**Comment by sapjax** [comment]
@tgxhx 
This is a nice idea, but it seems unsafe for users to paste GitHub token directly into the input. 
I plan to register the GitHub Application, and then users can take the OAuth flow to get the auth token. This process can limit the permissions to gists which related to this app, It would be better.

**Comment by tgxhx** [comment]
@sapjax 
Your consideration is reasonable.  I was inspired by the sync setting plugin of vscode, so I used a similar method of directly inputting the token.  However, using this on a browser indeed carries greater risks.

If you need to connect using the OAuth method for GitHub, you would need to register a GitHub OAuth application, which I am unable to do.  Do you have any plans or schedule to implement this feature?

**Comment by sapjax** [comment]
@tgxhx 
I just created a GitHub OAuth application, now I need to deal with the code about OAuth flow.
After that done, I will create a Pull Request to your fork repo, when it be merged, it will be shown in here.

**Comment by sapjax** [comment]
@tgxhx 
I found that the OAuth flow need a website backend to exchange the return `code` to `auth_token`, Otherwise, we have to expose the client_secret in the client.
I don't want to add any backend into this app, so I give up the OAuth flow.
I created a PR to your repo about some miner changes, you can review it first.

**Comment by tgxhx** [comment]
@sapjax I have merged the PR.

**Pull request merged**
